name: nubbe-env

channels:
  - conda-forge

dependencies:
  - python=3.10

  # ---- Required for download_nubbe.py ----
  - pandas
  - rdflib

  # ---- NOT needed yet (keep for later) ----
  # - jupyterlab
  # - numpy
  # - pytorch
  # - pytorch-geometric
  # - pytorch-sparse
  # - pytorch-cluster
  # - rdkit
  # - deepchem
  # - scikit-learn
  # - matplotlib
  # - seaborn
  # - plotly
  # - wandb
  # - tensorboard